### ISSUE TITLE
Integration user wallet repuation

### ISSUE THREAD

**Issue by SHUJAAT-DEV** [eLearningDAO/POCRE#100]
We have done the frontend UI part in ticket #73, now we need to integrate this part with backend. 

Backend API :
    https://pocre-api.herokuapp.com/v1/users/{USER_ID}

Frontend: 
    https://pocre.netlify.app/wallet

**Comment by AltiMario** [comment]
What I think is missing in this current wallet implementation deployed is:
- Reading and saving action
- Uploading a new avatar
- Link to actions like "Authors of X collection", "view creation", "new creation"
- Crypto wallet connections (it was implemented already there)

**Comment by AltiMario** [comment]
@SHUJAAT-DEV there is still a problem with the calculation of the wallet stars.
As you can see here 
![image](https://user-images.githubusercontent.com/598726/204668627-9b6f8a52-8593-4220-a428-edef22ac023c.png)
the user has lots of data stored but still 0 stars (it's wrong obviously).
Please read again how it should work https://github.com/e-Learning-DAO/POCRE/wiki/Wallet-reputation
