### ISSUE TITLE
Dispute details show wrong material related

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#188]
**Describe the bug**
The details of the dispute show the wrong material related. I think there is a bug in the query.

**To Reproduce**
Go to https://web-frontend--pocre.netlify.app/litigations/0a842fcc-d858-4049-a39b-b3838fc77c4e to see the litigation
and here https://web-frontend--pocre.netlify.app/recognitions/be8d7791-dfe4-4eff-baa8-c2a2dbff674d to see the correct claimed material.

![image](https://user-images.githubusercontent.com/598726/206856733-97df0b99-8c73-481e-a764-ce04281f08dd.png)

P.S.
Because you are going to fix this page, will be nice to remove the unnecessary "finger prints" there

**Comment by AltiMario** [comment]
please just check if it is a quick fix as I thought. If yes, go for it, otherwise we can leave it because not high priority

**Comment by UmairMukhtar** [comment]
Fixed in pull #234
