### ISSUE TITLE
search tool for user's wallet

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#215]
It is not possible to search for a user and display his wallet.

**Describe the solution you'd like**
We need to implement a search tool (like on GitHub) able to see brief info of the user before clicking on it.
I think showing the users' stars reputations is valuable info.

**Additional context**
There is a problem in the case of duplicated username. It is a very common scenario because it is not a unique field and by default is identified as "anonymous" (so a lot of anonymous will be displayed if you are looking for one of them). Probably, showing only the first 10 (?) matches (ordered by the last insertion) is good enough for the user experience.
It is currently a tool available only for not logged users (in the wallet section).

![image](https://user-images.githubusercontent.com/598726/208893811-60a23445-183d-4216-9e3b-72cc7c983927.png)

However, the feature will be used also for the recognition of the materials (partially implemented already)
![Screenshot_20221221_112737](https://user-images.githubusercontent.com/598726/208894874-47267383-2035-4643-8f1c-b0121c229f86.png)

**Comment by UmairMukhtar** [comment]
@huzaifa-99 @AltiMario should i import user suggestion hook from here https://github.com/eLearningDAO/POCRE/blob/32d26da5fbc9e7dc6847360de5cc5c66efe0e74f/app/web-frontend/src/pages/Creations/common/form/useCreationForm.jsx#L126 or should create a new file for explore wallet page

**Comment by AltiMario** [comment]
I have to open it again because the user reputation stars are not displayed during the material selection. It is well described in this ticket description.

**Comment by UmairMukhtar** [comment]
okay will be done

**Comment by UmairMukhtar** [comment]
FIxed in https://github.com/eLearningDAO/POCRE/pull/294
