### ISSUE TITLE
Wallet micro bugs

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#256]
**Describe the bug**
There are a few micro issues on the wallet page:
1- The logged avatar has to link to the wallet page (not the wallet profile), otherwise the logged user cannot easily understand how to edit the profile
2- Unless I did a wrong test, the user (of the screenshot) has enough info in his profile to achieve a 3-star reputation.
3- The counter of the creation sadly never worked 
3.1- And The button/label has to be a link to the user creations

**To Reproduce**
Go to https://deploy-preview-251--pocre.netlify.app/wallet/1529512c-d0b6-40f9-8a10-3a38a860a0dd

**Screenshots**
![image](https://user-images.githubusercontent.com/598726/211573823-c4363884-2bc7-449b-9b3c-787753cdf359.png)

**Comment by UmairMukhtar** [comment]
fixed in https://github.com/eLearningDAO/POCRE/pull/264

**Comment by AltiMario** [comment]
I just found out that 3.1 doesn't work.
It shows 
An help to reproduce: 
1- Access with your user using your wallet.
2- go to Mario's  wallet https://pocre.netlify.app/wallet/b0b2b418-764e-4454-940b-6494a8e3cf88
3- you can see 0 creations (or the number of creations your user has) but Mario has 4 creations
This "number of creations" is related to the wallet displayed and not the user logged
The link has to go to the creation of the wallet displayed and NOT the creation of the user logged
![image](https://user-images.githubusercontent.com/598726/214865645-e58157fa-9703-4fee-ab85-2f17dc03bc25.png)

on click, it has to show Mario's creations
![image](https://user-images.githubusercontent.com/598726/214866237-59edd103-7fef-48b9-9065-94c59edd9347.png)
(fix also the label by putting the name of the creator)
