### ISSUE TITLE
user profile email verification

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#258]
The user is able to change the email at any time (because it is not its unique id, where the wallet is the unique id).
In order to avoid fake profiles we have to provide a basic system of email verification.

When the user change (or add a new email the first time) the email from his profile (and click submit) a verification email is sent and a "pending" button is displayed on the page
![image](https://user-images.githubusercontent.com/598726/211790271-ffcbe874-4c54-43c5-a22a-c4f4a8ed708a.png)
On click to the button, the user can send another verification email (just in case it went "lost") but ask for confirmation in a popup before sending another email.
When the user receives the email and clicks on the verification link, the email in the user profile is verified and so again displayed.

We have already done an email verification process for the users invited to the platform, this function will reuse almost everything.

**Comment by UmairMukhtar** [comment]
@AltiMario i recomment the Pending Verification button should not be on edit screen rather it should be on view personal profiel screen as in the above image is is replacing the email textbox let say the user entered false email by mistake then this button will replace the text box and they will not be able to change the email an neither verify it

**Comment by AltiMario** [comment]
@UmairMukhtar A message can be something simple like "This email need to be verified, please click on the link" (I will change it later if needed).
Good point about the visualisation of the "pending verification" button.
