### ISSUE TITLE
Drafting each step of multi process workflows

### ISSUE THREAD

**Issue by huzaifa-99** [eLearningDAO/POCRE#282]
### Background
Currently during a creation, if the user quits (closes the tab/browser) on any step without saving the draft, they lose their progress. This is the same for litigation. It gets annoying if there is a lot of filled in form data.

### Action Items

- [x] 1. Each step of the creation should be automatically drafted until published by the user
- [x] 2. Each step of the litigation should be automatically drafted until published by the user.

**Comment by AltiMario** [comment]
I'm testing even if it is not completed yet, to help your development process. I found this issue when I was trying to save the draft

![Screenshot_20230216_113950](https://user-images.githubusercontent.com/598726/219355459-ad44a3fc-042d-4dd6-8d39-4cfd13bf3c24.png)

of a creation with these 2 materials
![image](https://user-images.githubusercontent.com/598726/219355615-b2f37024-3a6b-46a2-ab67-6aab6e994672.png)
