### ISSUE TITLE
Further tuning of the user profile page

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#285]
1- When the user logs in and accesses his profile, sometimes he got confused between his profile and other users' profile because the look & feel is the same. I'm proposing a modification (even if not beautiful) to make it more clear by simply changing the colour background of the gradient (propose a couple of options).
![image](https://user-images.githubusercontent.com/598726/214678852-540688d8-1bb4-4292-8977-d46d00900335.png)
For the other users (not the logged-in) keep the current gradient.
done :green_circle: 

2- because the user ID cannot be verified, use this image instead
![user-not-verified](https://user-images.githubusercontent.com/598726/214677584-828804d6-20bf-4055-9ca9-c4ec82f2762b.png)
the other with the green logo can be used in the future
not-sure if done :yellow_circle: 

3-  When the user (in the example David) is logged in and searches for other users, don't display the button (but only the label) "pending validation" because there is nothing to click.  
![image](https://user-images.githubusercontent.com/598726/214680466-b4b1f012-c85d-4655-a8bc-f55019e8b564.png)
If the user email is verified write "Email verified"
partially done :yellow_circle: 

4- If an email is used and verified (not pending), it cannot be used for another account. 
This is to avoid multiple wallets having the same email, in order to avoid problems during the user invitation by email.
not done :red_circle:

**Comment by AltiMario** [comment]
task status: 
1 - done :green_circle: 
2 - I'm not sure about the logic you applied there. This image is unrelated to the email verification. 
3 - done :green_circle:

**Comment by UmairMukhtar** [comment]
fixed in 
https://github.com/eLearningDAO/POCRE/pull/288
