### ISSUE TITLE
fix links and bio during the litigation process

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#291]
The descriptions (bios) of the contenders (during the litigation process) are wrong.
There are also links to jury members' profiles that need to be removed (because the jury act anonymously).

![wrong-info-dispute](https://user-images.githubusercontent.com/598726/216791149-7d9a837b-223c-4a83-aa89-31d4d632106c.png)

**Comment by UmairMukhtar** [comment]
Fixed In https://github.com/eLearningDAO/POCRE/pull/312
