### ISSUE TITLE
Youtube linking doesn't work

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#292]
During the creation and material recognition, the file-type auto detection cannot recognise anymore youtube video links.

![no-youtube](https://user-images.githubusercontent.com/598726/216791744-0f406349-d618-4039-bae5-a33384fce242.png)
![image](https://user-images.githubusercontent.com/598726/216791842-9675c9d3-b988-4efa-bfe5-e6e1f8ff2b40.png)

Would be nice to support also vimeo and file-sharing services.

**Comment by AltiMario** [comment]
a strange behaviour when you to add 2 materials as youtube videos  
![image](https://user-images.githubusercontent.com/598726/223095240-79f3bb73-14b6-4904-a23c-17f5e8f4a6b6.png)
test here https://main--pocre.netlify.app/creations/ba028e76-b29f-4510-9dcc-3f5c3c0e9e59

**Comment by UmairMukhtar** [comment]
![image](https://user-images.githubusercontent.com/34018917/224335759-7e1ad771-17a1-404b-a8b9-c04f560f05f7.png)

tested here 
 https://main--pocre.netlify.app/creations/ba028e76-b29f-4510-9dcc-3f5c3c0e9e59
