### ISSUE TITLE
Voting warning missing

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#338]
The full page of voting is not clear for the voters.
This page is good for the users that want to see the status of the voting (without interaction), but for the jury members it is very cryptic.
A new design/refactoring/simplification/clarification is needed, please propose your solution in the comments (with screenshots before any implementation).
Anyway, one of the main problems is the voting action which is currently buggy, as you can see from the video 
[voting-click.webm](https://user-images.githubusercontent.com/598726/224518703-db1d2848-407d-4fd9-b41f-82dc0681aea1.webm)

I think **at least** a message in a popup for the user is needed, to warn him that he is about to vote and the vote is "one time".

**Comment by UmairMukhtar** [comment]
Okay
